apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app-1
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: app1.com
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: app-1-service
            port:
              number: 42
  - host: app2.com
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: app-2-service
            port:
              number: 1337
  - host: app3.com
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: app-3-service
            port:
              number: 24