ssh_pub_key = File.readlines("#{ENV['HOME']}/.ssh/id_ed25519.pub").first.strip
server_ip = "192.168.42.110"

$k3s_server_script = <<-SCRIPT
echo "Start installation of k3s in the server"
sudo curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--flannel-iface 'eth1'" sh -
sudo chmod 777 /etc/rancher/k3s/k3s.yaml
SCRIPT

$ssh_config_script = <<-SCRIPT
echo "Adding ssh pulbic key to the guest"
echo '#{ssh_pub_key}' >> /home/vagrant/.ssh/authorized_keys
SCRIPT

$docker_setup_script = <<-SCRIPT
sudo yum check-update
sudo curl -fsSL https://get.docker.com/ | sh
sudo systemctl start docker
SCRIPT

$skaffold_setup_script = <<-SCRIPT
sudo curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
sudo install skaffold /usr/local/bin/
SCRIPT


Vagrant.configure("2") do |config|

  config.vm.box = "centos/8"

  config.vm.define "mfilahiS" do |control|
    control.vm.hostname = "mfilahiS"
    control.vm.network  "private_network", ip: server_ip
    control.vm.provider "virtualbox" do |vb|
      vb.name = "mfilahiS"
      vb.memory = 512
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      vb.customize ["modifyvm", :id, "--audio", "none"]
    end
    control.vm.provision "shell", inline: $ssh_config_script
    control.vm.provision "shell", inline: $k3s_server_script
    control.vm.provision "shell", inline: $docker_setup_script
    control.vm.provision "shell", inline: $skaffold_setup_script
  end
end
