ssh_pub_key = File.readlines("#{ENV['HOME']}/.ssh/id_ed25519.pub").first.strip
server_ip = "192.168.42.110"

$k3s_server_script = <<-SCRIPT
  echo "Start installation of k3s in the server"
  sudo curl https://releases.rancher.com/install-docker/19.03.sh | sh
  sudo curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--flannel-iface 'eth1' server --no-deploy traefik" sh -s - --docker
  sudo chmod 777 /etc/rancher/k3s/k3s.yaml
SCRIPT

$ssh_config_script = <<-SCRIPT
  echo "Adding ssh pulbic key to the guest"
  echo '#{ssh_pub_key}' >> /home/vagrant/.ssh/authorized_keys
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.box = "centos/8"

  config.vm.define "mfilahiS" do |control|
    control.vm.hostname = "mfilahiS"
    control.vm.network  "private_network", ip: server_ip
    control.vm.provider "virtualbox" do |vb|
      vb.name = "mfilahiS"
      vb.memory = 1024
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      vb.customize ["modifyvm", :id, "--audio", "none"]
    end
    control.vm.provision "shell", inline: $ssh_config_script
    control.vm.provision "shell", inline: $k3s_server_script
    control.trigger.after :up, :provision do |trigger|
      trigger.run_remote = {path: "./scripts/deploy.sh"}
    end
  end
end
