ssh_pub_key = File.readlines("#{ENV['HOME']}/.ssh/id_ed25519.pub").first.strip
server_ip = "192.168.42.110"
worker_ip = "192.168.42.111"
k3s_server_url = "https://192.168.42.110:6443"

$k3s_server_script = <<-SCRIPT
curl -sfL https://get.k3s.io | sh -
SCRIPT

$ssh_config_script = <<-SCRIPT
echo '#{ssh_pub_key}' >> /home/vagrant/.ssh/authorized_keys
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.box = "centos/8"

  config.vm.define "mfilahiS" do |control|
    control.vm.hostname = "mfilahiS"
    control.vm.network  "private_network", ip: server_ip
    control.vm.provider "virtualbox" do |vb|
      vb.name = "mfilahiS"
      vb.memory = 512
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      config.vm.provision "shell", inline: $ssh_config_script
      config.vm.provision "shell", inline: $k3s_server_script
      vb.customize ["modifyvm", :id, "--audio", "none"]
    end
   
  end

  config.vm.define "ismailSW" do |control|
    system('vagrant ssh -c "sudo cat /var/lib/rancher/k3s/server/node-token" | read K3S_SERVER_TOKEN');
    system('echo $K3S_SERVER_TOKEN');
    control.vm.hostname = "ismailSW"
    control.vm.network  "private_network", ip: worker_ip
    control.vm.provider "virtualbox" do |vb|
      vb.name = "ismailSW"
      vb.memory = 512
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      puts '#ENV["K3S_SERVER_TOKEN"]'
      $k3s_client_script = <<-SCRIPT
        curl -sfL https://get.k3s.io | K3S_URL=#{k3s_server_url} K3S_TOKEN=#{ENV["K3S_SERVER_TOKEN"]} sh -
      SCRIPT
      puts $k3s_client_script
      config.vm.provision "shell", inline: $ssh_config_script
      config.vm.provision "shell", inline: $k3s_client_script
      vb.customize ["modifyvm", :id, "--audio", "none"]
    end
  end
end
